config/routes.rb
Rails.application.routes.draw do
  root 'events#top'
  #get '/login', to: 'users#login'
  #get '/signup', to: 'users#create'
  get 'users/index'
  post 'users/index', to: 'users#update', as: 'users_update'
  get 'events/show/:id', to: 'events#show', as: 'events_show'
  get 'events/create'
  post 'events/create', to: 'events#new', as: 'events_new'
  post 'rsvp_create', to: 'events#rsvp_create', as: 'rsvp_create'
  post 'events/delete/:id', to: 'events#delete', as: 'event_delete'
  post 'events/edit/:id', to: 'events#edit', as: 'event_edit'
  put 'events/edit/:id', to: 'events#update', as: 'event_update'
  get '/contact', to: 'contact#new', as: 'contact_new'
  post '/contact', to: 'contact#create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/models/event.rb
class Event < ApplicationRecord
    validates :event_name, presence: true, length: { maximum: 50 }
    validates :description, presence: true, length: { maximum: 500}
    validates :event_date, presence: true
    validates :location, presence: true, length: { maximum: 255}

    geocoded_by :location
    after_validation :geocode, :if => :location_changed?
    #validates :latitude, presence: true
    has_many :rsvps, dependent: :destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  def top
    @events = Event.all
  end

  def show  
    @event = Event.find(params[:id])
    id = @event[:creator_id]
    @creator = User.find(id)
    show_set_json
    
  end

  def create
    # This action is to display an event create page.
  end

  def new
    eventdate = DateTime.parse(params[:date].to_s+ ' ' + params[:time].to_s).to_s(:db) if (params[:date]!= "" && params[:time] != "") # .to_s(:db)で秒情報まで取得
    
    @event = Event.new(event_name: params[:event_name], description: params[:description], event_date: eventdate, location: params[:location], creator_id: current_user.id )
      #event[:creator_id]= current_user.id
      if @event.save 
        redirect_to events_show_path(@event.id)
      else
        render 'create' and return# This 'return' is to end this method.
      end

  end

  def rsvp_create
    if current_user.id != Event.find(params[:event_id]).creator_id
      rsvp = Rsvp.new(event_id: params[:event_id], user_id: current_user.id)
      rsvp.save
      UserMailer.with(user: current_user, event_id: params[:event_id]).rsvp_email.deliver_now
      redirect_to(events_show_path(params[:event_id]))
    end
  end

  def delete 
    event = Event.find(params[:id])
    receivers = []
    Rsvp.where(event_id: params[:id]).each do |r|
      # puts "********************** delete ***********************"
      # puts r.user_id
      receivers.push(User.find(r.user_id))
    end
    delete_event_destroy(event, receivers)
    
  end

  def edit
    @event = Event.find(params[:id])
    #puts @event[:event_date]
    @date = @event[:event_date].strftime("%Y-%m-%d")
    @time = @event[:event_date].strftime("%H:%M")
    #puts @date
    
  end

  def update
    event_updated = Event.find(params[:id])
    @date = event_updated[:event_date].strftime("%Y-%m-%d")
    @time = event_updated[:event_date].strftime("%H:%M")
    update_change_event(event_updated)
    update_event_save(event_updated)  
  end

  private

  def show_set_json
    if (@event[:latitude]!=nil &&@event[:longitude] != nil)
      respond_to do |format|
        format.html
        format.json do 
          render json:  { type: 'Feature', geometry: { type: 'Point', coordinates: [@event.latitude, @event.longitude] }, properties: { name: @event.event_name, location: @event.location }}
        end
      end
    end
  end

  def delete_event_destroy(event, receivers)
    if event.destroy
      #puts "****************** deleted ************************" 
      receivers.each do |rece|
        #puts rece.email
        UserMailer.with(receiver: rece, cancelled_event: event).delete_confirm_mail.deliver_now
    
      end
      
      redirect_to(root_path)
    else
      redirect_to(events_show_path(params[:id]))
    end
  end

  def update_change_event(event_updated)
    event_updated[:event_name] = params[:event_name]
    event_updated[:description] = params[:description]
    
    dateTime = DateTime.parse(params[:date] + ' ' + params[:time]).to_s(:db) if params[:date]!= "" && params[:time] != ""
    event_updated[:event_date] = dateTime
    event_updated[:location] = params[:location]
  end

  def update_event_save(event_updated)
    if event_updated.save 
      flash[:success] = 'The event has been successfully updated.'
      redirect_to(events_show_path(event_updated.id))
    else
      render 'edit' and return
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/create.html.erb
<% if @event != nil %>
  <div class="alert alert-warning">
    <ul>
      <% @event.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h3>Event Create</h3>
<%=  form_with(url: events_new_path, method: :post, local: true) do |form| %>
    <table>
    <tr>
        <td>Event Date</td>
        <td class="tbox1"><%= form.date_field :date, value: params[:date]||Date.today %>
        <%= form.time_field :time, value: params[:time]|| "12:00" %></td>
    </tr>
    <tr>
        <td>Event Title</td>
        <td class="tbox1"><%= form.text_field :event_name, class: "tbox_input", value: params[:event_name] %></td>
    </tr>
    <tr>
        <td>The Description</td>
        <td class="tbox1"><%= form.text_area :description, class: "tbox_input", value: params[:description] %></td>
    </tr>
    <tr>
        <td>The Location</td>
        <td class="tbox1"><%= form.text_area :location, class: "tbox_input", value: params[:location] %></td>
    </tr>
    </table>
    <input type="submit" value="Submit">
<% end %>
    

app/views/events/edit.html.erb
<% if @event != nil %>
  <div class="alert alert-warning">
    <ul>
      <% @event.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h3>Event Edit</h3><br>
<%=  form_with(url: event_update_path, method: :put, local: true) do |form| %>
    <table>
    <tr>
        <td>Event Date</td>
        <td class="tbox1"><%= form.date_field :date, value: @date %>
        <%= form.time_field :time, value: @time %></td>
    </tr>
    <tr>
        <td>Event Title</td>
        <td class="tbox1"><%= form.text_field :event_name, class: "tbox_input", value: @event[:event_name] %></td>
    </tr>
    <tr>
        <td>The Description</td>
        <td class="tbox1"><%= form.text_area :description, class: "tbox_input", value: @event[:description] %></td>
    </tr>
    <tr>
        <td>The Location</td>
        <td class="tbox1"><%= form.text_area :location, class: "tbox_input", value: @event[:location] %></td>
    </tr>
    </table>
    <%= form.submit "Submit" %>
<% end %>
    

app/views/events/show.html.erb
<h3>Event Description Page</h3><br>
<%= flash[:success] %>
<div class="waku2">
    <p><%= @event[:event_date].strftime("%A/ %d/ %m/ %Y %H:%M") %></p><br>
    <p><%= @event[:event_name] %></p>
    <p>Creator:<%= @creator.name %></p>
    <% if current_user != nil %>
        <%= form_with(url: rsvp_create_path, method: :post, local: true) do |form| %>
        <%= form.hidden_field :event_id, value: @event[:id] %>
            <%  if current_user != @creator %>
                <% if rsvpCheck(@event[:id]) == true %>
                    <%= form.submit value: "RSVP Submitted", disabled: true %>
                <% else %>
                    <%= form.submit value: "RSVP" %>
                <% end %>
            <% end %>
        <% end %>
    <% else %>
        <%= form_with(url: login_path, method: :get, local: true) do |form| %>
            <%= form.submit value: "log in" %>
        <% end %>
    <% end %>

    <% if can? :update, @event %>
    <div class="event_show_edit"  >
        <%= form_with(url: event_edit_path, method: :post, local: true) do |form| %>
        <%= form.submit value: "Edit" %>
        <% end %>
        <%= form_with(url: event_delete_path, method: :post, local: true) do |form| %>
        <%= form.submit value: "Delete", data: { confirm: "Are you sure to delete it?"} %>
        <% end %>
    </div>
    <% end %>


    
    
    
    
</div>
<div class="waku4">
    <div class="waku">
    <p>Event Description</p><br>
    <p><%= @event[:description] %></p>
    </div>
    <div class="waku">
        <p>Joined Members</p>
        <ul>
            <% @members=getRsvpMembers(@event.id) %>
            <% @members.each do |m| %>
                <li><%= m.name %></li>
            <% end %>
        </ul>
    </div>
   
    
    </div>
    <div class="waku waku4">
        <div id="display1"></div>
        <div id="display2"></div>
        <div id="map"></div>
       <div class="hr"></div>
       <div><%= @event[:location] %></div>
    </div>
</div>

<%= javascript_include_tag 'event.js' %>

app/views/events/top.html.erb
<h2>Events</h2>
<div class="people_image" col-12>
    <%= image_tag('https://reunimos-bucket.s3-ap-southeast-2.amazonaws.com/people-1230872_1280.jpg') %>
</div>
<div >
    <ul>
        <% @events.each do |e| %>
            <%= form_with url:root_path, method: :post, local: true do |form| %> 
                <li>
                    <div class="waku">
                        <div><%= e[:event_date].strftime("%A/ %d/ %m/ %Y %H:%M") %></div>
                        <div><%= link_to e.event_name, events_show_path(e.id) %></div>
                        <%= form.hidden_field :event_id, value: e.id %>
                        <% if current_user != nil && rsvpCheck(e[:id]) == true %>
                            <%= "RSVP Sumitted" %>
                        <% end %>
                    </div>
                </li>
            <% end %> 
        <% end %>
    </ul>
</div>