config/routes.rb
Rails.application.routes.draw do
  root 'events#top'
  #get '/login', to: 'users#login'
  #get '/signup', to: 'users#create'
  get 'users/index'
  post 'users/index', to: 'users#update', as: 'users_update'
  get 'events/show/:id', to: 'events#show', as: 'events_show'
  get 'events/create'
  post 'events/create', to: 'events#new', as: 'events_new'
  post 'rsvp_create', to: 'events#rsvp_create', as: 'rsvp_create'
  post 'events/delete/:id', to: 'events#delete', as: 'event_delete'
  post 'events/edit/:id', to: 'events#edit', as: 'event_edit'
  put 'events/edit/:id', to: 'events#update', as: 'event_update'
  get '/contact', to: 'contact#new', as: 'contact_new'
  post '/contact', to: 'contact#create'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to image_tag('https://reunimos-bucket.s3-ap-southeast-2.amazonaws.com/logo2.png'), root_path %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= current_user.name %>
        <% if can? :index, current_user %>
          <li><%= link_to "Admission Page", users_index_path %></li>
        <% end %>
        <% if can? :create, current_user %>
          <li><%= link_to "Event Create", events_create_path %></li>
        <% end %>
        <li><%= link_to "Log out", logout_path %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
      <% end %> 
      <li><%= link_to "Contact us", contact_new_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Reunimos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>